spring:
  datasource:
    url: jdbc:mysql://localhost/board
    username: root
    password: 

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

page:
  topTitle: トップページ
  topUrl: /top

board:
  title:
    top: TOPページ
    topUrl: /top
    main: MAINページ
    mainUrl: /main